participant: "Fluid"
meshes:
  - mesh: "Fluid-Mesh"
    meshfileprefix: /home/kursatyurt/tutorials/perpendicular-flap/fluid-nutils/Fluid_VTK/Fluid-Mesh-Fluid
    read-data:
      vector: [Displacement]
      scalar: [abc]
    write-data:
      vector: [Force]
      scalar: [abc]
precice-config: "../precice-config.xml"
